jobs:
ui-tests:
name: UI Tests
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repo
    uses: actions/checkout@v4

  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 20

  - name: Install dependencies
    run: npm ci

  - name: Install Playwright Browsers
    run: npx playwright install --with-deps

  - name: Run UI tests
    run: npm run test:ui

  - name: Upload UI Report
    if: always()
    uses: actions/upload-artifact@v4
    with:
      name: ui-report
      path: playwright-report/
```

api-tests:
name: API Tests
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repo
    uses: actions/checkout@v4

  - name: Setup Node
    uses: actions/setup-node@v4
    with:
      node-version: 20

  - name: Install dependencies
    run: npm ci

  - name: Run API tests
    run: npm run test:api

  - name: Upload API Report
    if: always()
    uses: actions/upload-artifact@v4
    with:
      name: api-report
      path: playwright-report/
```